### ISSUE TITLE
Make install fails

### ISSUE THREAD

**Issue by hosseinsalahi** [wayfair/terraform-provider-foreman#1]
correct form: make && make install

**Comment by mcgarebear** [comment]
Hello encodeflush,

Thank you for bringing this to our attention - I will be allocating some time to get this resolved for you. 

Can you please provide where/how the `install` target is failing as well as more information (ie: are you running Windows/MacOS/Linux, etc)? Any console output or screenshots would be appreciated. Or is this issue more about the Makefile workflow?

- Brendan

**Comment by hosseinsalahi** [comment]
OS: Arch linux
error:
`make: *** No rule to make target 'build/_/foreman/terraform-provider-foreman_ca9d68c_x4', needed by 'install'.  Stop.`

As I mentioned earlier, `make` before `make install` solved my problem.

**Comment by mcgarebear** [comment]
Gotcha! Thanks for the clarification - I will work on getting that corrected

**Comment by mcgarebear** [comment]
Corrected in `0843b092eb15a46e9a1c63cfd4d645e6bfc7de43`
