### ISSUE TITLE
Working on new features for the provider

### ISSUE THREAD

**Issue by lhw** [wayfair/terraform-provider-foreman#2]
I found this provider to be well written and want to use this internally for our IaaS approach. Which will combine use of bare metal and virtual machines managed by the same Foreman instance. So I thought I would add a few more features to the provider. I currently have already added the features required to manage and start VMs aside from bare metal machines.

I'll add the first two pull requests ahead of time but I thought I should probably also discuss what you intend for this provider as it seems to be already in production use and I don't want to tread on anyones feet here.

Related Pull Requests: #3 #4 #5

**Comment by mcgarebear** [comment]
@lhw 

Thank you for showing interest in using our provider!

I have brought this issue up with my team and we will be evaluating your guys' contributions during standups. I don't see why we wouldn't be able to work something out. As you've noted, we do primarily use this provider internally for provisioning our physical hosts (we use another open-sourced provider for provisioning our virtual machines), but I personally don't see that as a blocker to any progress. I will keep in touch.

- Brendan

**Comment by lhw** [comment]
I'm still working on it right now. The pull requests were just an example on what features I want to add on top of fixing up the bare metal provisioning. The fork under https://github.com/HanseMerkur/terraform-provider-foreman has the most recent changes. I noticed a few bugs with in-place upgrades that I already fixed. When everything works I will create the appropriate pull requests here.

**Comment by lhw** [comment]
At this point my version is so far ahead that merging back would probably be more work. Closing this
